language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r baseline/requirements.txt
  - unzip data/xstance-data-v1.0.zip -d data
script: python evaluate.py --gold data/test.jsonl --pred predictions/pred.jsonl
